version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4335:4321"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # Para desarrollo, se puede descomentar esta configuración
  # dev:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   command: npm run dev -- --host 0.0.0.0
  #   ports:
  #     - "4321:4321"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #   restart: unless-stopped 